project_name = 'relate'

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.provider :virtualbox do |vb|
    vb.name = project_name
  end
  config.vm.network :private_network, ip: "192.168.114.101"
  config.vm.synced_folder "..", "/home/vagrant/workspace/#{project_name}", :owner => 'vagrant', :group => 'www-data', :mount_options => ["dmode=775"]
  config.vm.hostname = "#{project_name}.local"

  config.vm.provision :chef_solo do |chef|

    chef.add_recipe("relate")
    chef.add_recipe("relate::refresh_apt_get")
    chef.add_recipe("relate::apache_setup")
    chef.add_recipe("relate::mysql_setup")
    chef.add_recipe("relate::vagrant_user")

    chef.json = {
      :project => {
        :name => project_name,
        :type => "php",
        :profile_name => "standard",
        :base_url => "http://#{project_name}.local"
      },
      :mysql => {
        :server_root_password => "root",
        :server_repl_password => "root",
        :server_debian_password => "root"
      }
    }
  end
end